# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_doc', '0006_auto_20171021_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='recommender',
        ),
        migrations.AddField(
            model_name='membership',
            name='recommender',
            field=models.ManyToManyField(related_name='recommend_membership_set', to='models_doc.Idol'),
        ),
    ]
