# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_doc', '0009_school_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_type', models.CharField(choices=[('magician', '마법사'), ('supporter', '서포터'), ('ad', '원거리 딜러')], max_length=20)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '챔피언',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Midliner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('models_doc.champion',),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('models_doc.champion',),
        ),
    ]
