# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_doc', '0010_champion_midliner_supporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInheritance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ABC', max_length=50)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_places', models.ManyToManyField(related_name='supply_place_set', related_query_name='supply_place', to='models_doc.PlaceInheritance')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models_doc.Place'),
        ),
    ]
